import { jsPDF } from "jspdf";

export type ItrData = {
  recommended_form?: string;
  assessment_year?: string;
  regime?: string;
  personal?: Record<string, string | null>;
  income?: Record<string, number | null>;
  deductions?: Record<string, number | null>;
  tax?: Record<string, number | null>;
  bank?: Record<string, string | null>;
  notes_for_user?: string;
};

const fmt = (n: number | null | undefined) =>
  typeof n === "number" && !isNaN(n) ? `Rs. ${n.toLocaleString("en-IN")}` : "—";

const txt = (v: string | null | undefined) => (v ? String(v) : "—");

const sum = (obj?: Record<string, number | null>) =>
  obj ? Object.values(obj).reduce((a: number, b) => a + (typeof b === "number" ? b : 0), 0) : 0;

export const generateItrPdf = (data: ItrData) => {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const W = doc.internal.pageSize.getWidth();
  let y = 50;

  const h1 = (s: string) => {
    doc.setFont("helvetica", "bold"); doc.setFontSize(16);
    doc.text(s, 40, y); y += 22;
  };
  const h2 = (s: string) => {
    doc.setFont("helvetica", "bold"); doc.setFontSize(12);
    doc.setFillColor(232, 240, 254); doc.rect(40, y - 12, W - 80, 18, "F");
    doc.setTextColor(20, 60, 140); doc.text(s, 46, y);
    doc.setTextColor(0, 0, 0); y += 18;
  };
  const row = (k: string, v: string) => {
    doc.setFont("helvetica", "normal"); doc.setFontSize(10);
    doc.text(k, 46, y);
    doc.setFont("helvetica", "bold"); doc.text(v, W - 46, y, { align: "right" });
    y += 16;
    if (y > 780) { doc.addPage(); y = 50; }
  };
  const para = (s: string) => {
    doc.setFont("helvetica", "normal"); doc.setFontSize(10);
    const lines = doc.splitTextToSize(s, W - 92);
    doc.text(lines, 46, y); y += lines.length * 13 + 4;
  };

  // Header
  doc.setFillColor(15, 15, 15);
  doc.rect(0, 0, W, 36, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold"); doc.setFontSize(13);
  doc.text("AXCIS LEDGER  ·  ITR Working Sheet", 40, 23);
  doc.setTextColor(0, 0, 0);
  y = 60;

  h1(`${txt(data.recommended_form) || "ITR"} — ${txt(data.assessment_year) || "AY 2025-26"}`);
  doc.setFont("helvetica", "normal"); doc.setFontSize(9); doc.setTextColor(100);
  doc.text(
    "This is an AI-prepared working sheet to help you file your ITR on the official Income Tax portal. Verify all numbers before filing.",
    40, y, { maxWidth: W - 80 }
  );
  doc.setTextColor(0, 0, 0); y += 24;

  h2("Personal details");
  const p = data.personal || {};
  row("Name", txt(p.name));
  row("PAN", txt(p.pan));
  row("Date of birth", txt(p.dob));
  row("Mobile", txt(p.mobile));
  row("Email", txt(p.email));
  row("Address", txt(p.address));
  row("Aadhaar (last 4)", txt(p.aadhaar_last4));
  row("Tax regime", txt(data.regime));

  h2("Income");
  const inc = data.income || {};
  row("Salary", fmt(inc.salary));
  row("House property", fmt(inc.house_property));
  row("Business / profession", fmt(inc.business_or_profession));
  row("Short-term capital gains", fmt(inc.short_term_capital_gains));
  row("Long-term capital gains", fmt(inc.long_term_capital_gains));
  row("Other sources", fmt(inc.other_sources));
  const grossIncome = sum(inc);
  row("Gross total income", fmt(grossIncome));

  h2("Deductions / exemptions");
  const d = data.deductions || {};
  row("Standard deduction", fmt(d.std_deduction));
  row("HRA exempt", fmt(d.hra_exempt));
  row("Section 80C", fmt(d.sec_80c));
  row("Section 80D", fmt(d.sec_80d));
  row("Section 80CCD(1B)", fmt(d.sec_80ccd_1b));
  row("Section 80G", fmt(d.sec_80g));
  row("Home loan interest", fmt(d.home_loan_interest));
  const totalDed = sum(d);
  row("Total deductions", fmt(totalDed));

  const taxableIncome = Math.max(0, grossIncome - totalDed);
  row("Taxable income", fmt(taxableIncome));

  h2("Taxes paid");
  const t = data.tax || {};
  row("TDS", fmt(t.tds));
  row("Advance tax", fmt(t.advance_tax));
  row("Self-assessment tax", fmt(t.self_assessment_tax));

  h2("Bank account (for refund)");
  const b = data.bank || {};
  row("Bank", txt(b.bank_name));
  row("IFSC", txt(b.ifsc));
  row("Account (last 4)", txt(b.account_last4));

  if (data.notes_for_user) {
    h2("Notes from your AI CA");
    para(data.notes_for_user);
  }

  // Footer
  doc.setFontSize(8); doc.setTextColor(120);
  doc.text("Generated by Axcis Ledger · For your reference only · File on incometax.gov.in", W / 2, 820, { align: "center" });

  doc.save(`Axcis-ITR-${data.recommended_form || "draft"}-${Date.now()}.pdf`);
};
